# Generated by Django 3.1 on 2020-08-27 11:36

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200827_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpage',
            name='validaing',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
