# Generated by Django 3.1 on 2020-08-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_registerpage_validaing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joindata',
            name='team',
            field=models.CharField(choices=[('大冠隊', '大冠隊'), ('彩鷸隊', '彩鷸隊'), ('家雁隊', '家雁隊')], default='大冠隊', max_length=3),
        ),
    ]
