# Generated by Django 3.1 on 2020-08-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200824_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpage',
            name='des',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
