# Generated by Django 3.1 on 2020-08-24 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('home', '0004_normalpage_des'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NormalPage',
            new_name='HomePage',
        ),
    ]
