# Generated by Django 3.1 on 2020-08-24 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200824_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Title',
            new_name='Why',
        ),
    ]
