# Generated by Django 3.1 on 2020-08-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200824_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='Why',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='des',
        ),
    ]
