# Generated by Django 3.1 on 2020-09-08 13:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_pagefolder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='AppDemoPage',
        ),
    ]
