# Generated by Django 3.1 on 2020-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200908_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team1_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team2_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team3_name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
