# Generated by Django 3.1 on 2020-09-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0013_auto_20200909_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
