# Generated by Django 3.1 on 2020-09-11 08:22

from django.db import migrations, models
import wagtail.core.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_homepage_title_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='register_url',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team1_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team1_welcome_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team1_welcome_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team2_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team2_welcome_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team2_welcome_title',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team3_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', max_length=7),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team3_welcome_content',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team3_welcome_title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
