# Generated by Django 3.1 on 2020-09-13 06:30

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200911_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='corporation_icon1',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='corporation_icon2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='register_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team1_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team1_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team1_welcome_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team1_welcome_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team2_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team2_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team2_welcome_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team2_welcome_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team3_icon',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team3_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team3_welcome_content',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='team3_welcome_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='title_icon',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='dash_grah_id',
            field=models.CharField(help_text="Don't touch this value, the page may crash!!", max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team1_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='the color for 彩鷸隊', max_length=7),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team2_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='the color for 家燕隊', max_length=7),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team3_color',
            field=wagtail_color_panel.fields.ColorField(default='#ffffff', help_text='the color for 大冠鷲隊', max_length=7),
        ),
    ]
