# Generated by Django 3.1 on 2020-09-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('home', '0016_auto_20200913_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='upper_home',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('event1_title', models.CharField(help_text='秋季大亂鬥', max_length=30)),
                ('event1_description', models.CharField(max_length=150)),
                ('event1_period', models.CharField(max_length=20)),
                ('event2_title', models.CharField(help_text='全球觀鳥大日', max_length=30)),
                ('event2_description', models.CharField(max_length=150)),
                ('event2_period', models.CharField(max_length=20)),
                ('event2_url', models.CharField(help_text='10/17全球官鳥大日的網址', max_length=40)),
                ('event3_title', models.CharField(help_text='台北觀鳥大賽', max_length=30)),
                ('event3_description', models.CharField(max_length=150)),
                ('event3_period', models.CharField(max_length=20)),
                ('event1_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('event1_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('event2_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('event3_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('event3_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
