# Generated by Django 3.1 on 2020-09-29 19:09

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_upper_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upper_home',
            name='event1_description',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='upper_home',
            name='event2_description',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='upper_home',
            name='event3_description',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
