# Generated by Django 3.1 on 2020-09-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0002_auto_20200913_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamintroduction',
            name='reward_content',
        ),
        migrations.AddField(
            model_name='teamintroduction',
            name='team_left_description',
            field=models.CharField(blank=True, help_text='彩鷸隊', max_length=100),
        ),
        migrations.AddField(
            model_name='teamintroduction',
            name='team_middle_description',
            field=models.CharField(blank=True, help_text='家燕隊', max_length=100),
        ),
        migrations.AddField(
            model_name='teamintroduction',
            name='team_right_description',
            field=models.CharField(blank=True, help_text='大冠鷲隊', max_length=100),
        ),
    ]
