# Generated by Django 3.1 on 2020-09-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0003_auto_20200914_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebirdid', models.CharField(max_length=50)),
                ('team', models.CharField(choices=[('彩鷸隊', '彩鷸隊'), ('家燕隊', '家燕隊'), ('大冠鷲隊', '大冠鷲隊')], default='彩鷸隊', max_length=6)),
                ('email', models.EmailField(max_length=100)),
                ('signup_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
