# Generated by Django 3.1 on 2020-09-14 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0005_signuppage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('creator', models.CharField(max_length=30)),
                ('scrape_date', models.DateField(auto_now_add=True)),
                ('checklist_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('latitude', models.FloatField(default=23.5)),
                ('longitude', models.FloatField(default=120.5)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyObs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_code', models.CharField(default='aalife', max_length=10)),
                ('species_tranlated_name', models.CharField(default='unKnown', max_length=30)),
                ('amount', models.IntegerField(default=0)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fall.survey')),
            ],
        ),
    ]
