# Generated by Django 3.1 on 2020-09-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0006_survey_surveyobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_datetime',
            field=models.DateTimeField(null=True, verbose_name='調查時間'),
        ),
        migrations.AddField(
            model_name='survey',
            name='team',
            field=models.CharField(default='沒有隊', max_length=5),
        ),
    ]
