# Generated by Django 3.1 on 2020-09-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('fall', '0007_auto_20200915_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=40)),
                ('participant_email', models.EmailField(max_length=100)),
                ('guess_n_species', models.IntegerField(default=0)),
                ('guess_total_individual', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitPrediction',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
