# Generated by Django 3.1 on 2020-09-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0010_auto_20200920_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='IsDemoApp',
            field=models.BooleanField(default=True),
        ),
    ]
