# Generated by Django 3.1 on 2020-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0011_dashboard_isdemoapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyobs',
            old_name='species_tranlated_name',
            new_name='species_name',
        ),
        migrations.RemoveField(
            model_name='surveyobs',
            name='species_code',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='survey',
            name='region_code',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
