# Generated by Django 3.1 on 2020-09-23 06:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('fall', '0013_dashboard_brython_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutumnChallengePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('rules', wagtail.core.fields.RichTextField(blank=True)),
                ('prizes', wagtail.core.fields.RichTextField(blank=True)),
                ('dash_board_name', models.CharField(help_text="DON'tT TOUCH this", max_length=30)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='guess_n_species',
            field=models.IntegerField(default=0, verbose_name='幾種物種？'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='guess_total_individual',
            field=models.IntegerField(default=0, verbose_name='全部幾隻？'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='participant_email',
            field=models.EmailField(max_length=100, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='participant_name',
            field=models.CharField(max_length=40, verbose_name='參與者名稱'),
        ),
        migrations.AlterField(
            model_name='predictiondata',
            name='prediction_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='何時進行預測'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='ebirdid',
            field=models.CharField(max_length=50, verbose_name='ebird公開帳號'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='電子信箱'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='signup_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='報名時間'),
        ),
        migrations.AlterField(
            model_name='signupdata',
            name='team',
            field=models.CharField(choices=[('彩鷸隊', '彩鷸隊'), ('家燕隊', '家燕隊'), ('大冠鷲隊', '大冠鷲隊')], default='彩鷸隊', max_length=6, verbose_name='隊伍名稱'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='checklist_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='清單ID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='creator',
            field=models.CharField(max_length=30, verbose_name='清單分享來源'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='是否完整'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='latitude',
            field=models.FloatField(default=23.5, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='longitude',
            field=models.FloatField(default=120.5, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='region_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='區域代碼'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='scrape_date',
            field=models.DateField(auto_now_add=True, verbose_name='清單抓取日期'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='team',
            field=models.CharField(default='沒有隊', max_length=5, verbose_name='隊伍名稱'),
        ),
        migrations.AlterField(
            model_name='surveyobs',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='數量'),
        ),
        migrations.AlterField(
            model_name='surveyobs',
            name='species_name',
            field=models.CharField(default='unKnown', max_length=30, verbose_name='物種名稱'),
        ),
        migrations.AlterField(
            model_name='surveyobs',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fall.survey', verbose_name='清單ID'),
        ),
    ]
