# Generated by Django 3.1 on 2020-09-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0016_auto_20200925_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='region_code',
        ),
        migrations.AddField(
            model_name='survey',
            name='county',
            field=models.CharField(default='天國市地獄鎮', max_length=15, verbose_name='鄉鎮名稱'),
        ),
    ]
