# Generated by Django 3.1 on 2020-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0018_auto_20200928_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictiondata',
            name='participant_email',
        ),
        migrations.AddField(
            model_name='predictiondata',
            name='participant_phone',
            field=models.CharField(default='0912345678', max_length=30, verbose_name='聯絡電話'),
        ),
    ]
