# Generated by Django 3.1 on 2020-10-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fall', '0019_auto_20200928_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autumnchanllengedata',
            name='is_valid',
            field=models.BooleanField(verbose_name='有鳥才算數'),
        ),
    ]
